export const ADD_FRUIT = 'ADD_FRUIT';
export const FETCH_FRUITS_ADMIN = 'FETCH_FRUITS_ADMIN';

export const FETCH_SUCCEEDED_ADMIN = 'FETCH_SUCCEEDED_ADMIN';
export const FETCH_FAILED_ADMIN = 'FETCH_FAILED_ADMIN';

//Update
export const UPDATE_FRUIT = 'UPDATE_FRUIT';
export const UPDATE_SUCCEEDED = 'UPDATE_SUCCEEDED';

//Delete
export const DELETE_FRUIT = 'DELETE_FRUIT';
export const DELETE_SUCCEEDED = 'DELETE_SUCCEEDED';
