export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_SUCCEEDED_ORDER = 'FETCH_SUCCEEDED_ORDER';
export const FETCH_FAILED_ORDER = 'FETCH_FAILED_ORDER';

export const DELETE_ORDER = 'DELETE_ORDER';
export const DELETE_ORDER_SUCCEEDED = 'DELETE_ORDER_SUCCEEDED';